export const FETCH_BLOGS = "FETCH_BLOG"
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOG_SUCCESS"
export const FETCH_BLOGS_FAILURE = "FETCH_BLOG_FAILURE"

export const FTECH_BLOG_DETAILS = "FTECH_BLOG_DETAILS"
export const FTECH_BLOG_DETAILS_SUCCESS = "FTECH_BLOG_DETAILS_SUCCESS"
export const FTECH_BLOG_DETAILS_FAILURE = "FTECH_BLOG_DETAILS_FAILURE"